#!/usr/bin/env -S ruby --disable-gems
# frozen_string_literal: true

ORBIT_SCRIPT_PATH = File.expand_path(__FILE__)
ORBIT_ROOT = File.expand_path("..", File.dirname(ORBIT_SCRIPT_PATH))

require File.join(ORBIT_ROOT, "lib", "orbit", "v2", "cli")

exit run_v2_cli(ARGV)
