# frozen_string_literal: true

require "openssl"
require "securerandom"

require_relative "authority_verifier"
require_relative "canonical_json"
require_relative "errors"
require_relative "lifecycle_verifier"
require_relative "runtime_identity_verifier"

module Orbit
  module V2
    # Local HMAC providers for the minimal real CLI path (Slice 6 phase D).
    #
    # SCOPE AND TRUST MODEL (workorder D.3.1 adjudication, 2026-08-17):
    # in phase D the local provider is NOT a security mechanism — it is a
    # CONSISTENCY mechanism. It offers zero defense against a local
    # attacker who can read the key file (that attacker can already
    # rewrite the whole `.orbit` tree). Its real job is to make the
    # production verification path EXECUTE instead of being bypassed:
    # every controlled write still goes through AuthorityVerifier /
    # RuntimeIdentityVerifier / LifecycleVerifier exactly as a remote
    # provider would. Replacing these with real external providers is a
    # recorded debt (see docs/plan/debt-ledger.md, item 1).
    #
    # The key file is generated by `v2 init` at
    # `<project>/.orbit/local-provider.json`, is covered by the existing
    # `.orbit/*` gitignore rule, and is deliberately NOT committed: losing
    # it makes the project unverifiable (fail closed, no recovery path).
    module LocalProvider
      KEY_FILE_NAME = "local-provider.json".freeze
      SCHEMA_VERSION = "orbit-local-provider-v1".freeze
      AUTHORITY_PROVIDER_ID = "local.hmac.authority".freeze
      RUNTIME_PROVIDER_ID = "local.hmac.runtime".freeze
      LIFECYCLE_PROVIDER_ID = "local.hmac.lifecycle".freeze
      DEFAULT_ISSUER_SUBJECT = "local-user".freeze

      class << self
        def key_path(project_root)
          File.join(File.realpath(project_root), ".orbit", KEY_FILE_NAME)
        end

        # Creates the key file exactly once. An existing file is returned
        # as-is (:existing) so `v2 init` re-runs never rotate the secret.
        def ensure_key(project_root)
          path = key_path(project_root)
          return :existing if File.file?(path)

          require "fileutils"
          FileUtils.mkdir_p(File.dirname(path))
          record = {
            "schema_version" => SCHEMA_VERSION,
            "authority_provider_id" => AUTHORITY_PROVIDER_ID,
            "runtime_provider_id" => RUNTIME_PROVIDER_ID,
            "lifecycle_provider_id" => LIFECYCLE_PROVIDER_ID,
            "secret" => SecureRandom.hex(32),
            "issuer_subject" => DEFAULT_ISSUER_SUBJECT,
            "created_at" => Time.now.utc.iso8601(6)
          }
          File.open(path, File::Constants::WRONLY | File::Constants::CREAT | File::Constants::EXCL, 0o600) do |file|
            file.write(JSON.pretty_generate(record))
          end
          :created
        end

        def load_key(project_root)
          path = key_path(project_root)
          unless File.file?(path)
            raise ContractError.new(
              "local_provider_missing",
              "no #{KEY_FILE_NAME} under the project root; run `orbit v2 init` first",
              path: path
            )
          end
          record = JSON.parse(File.binread(path))
          unless record.is_a?(Hash) && record["schema_version"] == SCHEMA_VERSION &&
                 record["secret"].is_a?(String) && record["secret"].length >= 32
            raise ContractError.new(
              "local_provider_invalid",
              "local provider key file is malformed",
              path: path
            )
          end
          record
        rescue JSON::ParserError
          raise ContractError.new(
            "local_provider_invalid",
            "local provider key file is not valid JSON",
            path: path
          )
        end

        # The three verifiers every v2 command constructs, wired to the
        # local providers carrying the project key.
        def verifiers(project_root)
          key = load_key(project_root)
          [
            AuthorityVerifier.new(
              providers: { key["authority_provider_id"] => Authority.new(key["secret"]) }
            ),
            RuntimeIdentityVerifier.new(
              providers: { key["runtime_provider_id"] => Runtime.new(key["secret"]) }
            ),
            LifecycleVerifier.new(
              providers: { key["lifecycle_provider_id"] => Lifecycle.new(key["secret"]) }
            )
          ]
        end

        def issuer_subject(project_root)
          load_key(project_root)["issuer_subject"] || DEFAULT_ISSUER_SUBJECT
        end
      end

      module SecureCompare
        def self.equal?(left, right)
          left = left.to_s
          right = right.to_s
          return false unless left.bytesize == right.bytesize

          left.bytes.zip(right.bytes).reduce(0) { |diff, (a, b)| diff | (a ^ b) }.zero?
        end
      end

      class Authority
        def initialize(secret)
          @secret = secret
        end

        def issue(assertion, receipt_id:, issued_at:)
          body = {
            "schema_version" => AuthorityVerifier::RECEIPT_SCHEMA,
            "provider_id" => assertion["provider_id"],
            "receipt_id" => receipt_id,
            "project_id" => assertion["project_id"],
            "assertion_id" => assertion["assertion_id"],
            "assertion_digest" => assertion["assertion_digest"],
            "issuer_kind" => assertion["issuer_kind"],
            "issuer_subject" => assertion["issuer_subject"],
            "authority_scope_ref" => assertion["authority_scope_ref"],
            "grants" => assertion["grants"],
            "issued_at" => issued_at
          }
          body.merge("receipt" => signature(body))
        end

        def verify(receipt:, assertion_digest:, project_id:, assertion_id:)
          return false unless receipt["assertion_digest"] == assertion_digest &&
                              receipt["project_id"] == project_id &&
                              receipt["assertion_id"] == assertion_id

          SecureCompare.equal?(receipt["receipt"].to_s, signature(receipt.reject { |key, _v| key == "receipt" }))
        end

        private

        def signature(body)
          "hmac-sha256:#{OpenSSL::HMAC.hexdigest('SHA256', @secret, CanonicalJSON.dump(body))}"
        end
      end

      class Runtime
        def initialize(secret)
          @secret = secret
        end

        def issue(provider_id:, project_id:, agent_instance_id:, runtime_subject_id:)
          signature(
            "provider_id" => provider_id,
            "project_id" => project_id,
            "agent_instance_id" => agent_instance_id,
            "runtime_subject_id" => runtime_subject_id
          )
        end

        def verify(verification_receipt_ref:, provider_id:, project_id:, agent_instance_id:, runtime_subject_id:)
          expected = issue(
            provider_id: provider_id,
            project_id: project_id,
            agent_instance_id: agent_instance_id,
            runtime_subject_id: runtime_subject_id
          )
          SecureCompare.equal?(verification_receipt_ref.to_s, expected)
        end

        private

        def signature(body)
          "hmac-sha256:#{OpenSSL::HMAC.hexdigest('SHA256', @secret, CanonicalJSON.dump(body))}"
        end
      end

      class Lifecycle
        def initialize(secret)
          @secret = secret
        end

        def issue(event, project_id:, provider_id: LIFECYCLE_PROVIDER_ID)
          body = {
            "schema_version" => LifecycleVerifier::RECEIPT_SCHEMA,
            "provider_id" => provider_id,
            "receipt_id" => "olreceipt_#{event.fetch('event_id').delete_prefix('oevent_')}",
            "project_id" => project_id,
            "event_id" => event.fetch("event_id"),
            "event_type" => event.fetch("event_type"),
            "event_digest" => event.fetch("event_digest"),
            "recorded_at" => event.fetch("recorded_at")
          }
          body.merge("receipt" => signature(body))
        end

        def verify(receipt:, event_digest:, project_id:, event_id:, recorded_at:)
          return false unless receipt["event_digest"] == event_digest &&
                              receipt["project_id"] == project_id &&
                              receipt["event_id"] == event_id &&
                              receipt["recorded_at"] == recorded_at

          SecureCompare.equal?(receipt["receipt"].to_s, signature(receipt.reject { |key, _v| key == "receipt" }))
        end

        private

        def signature(body)
          "hmac-sha256:#{OpenSSL::HMAC.hexdigest('SHA256', @secret, CanonicalJSON.dump(body))}"
        end
      end
    end
  end
end
